/* resourcemap.js generated by blorbtool.py */
StaticImageInfo = {
1: {
  "image": 1,
  "url": "interpreter/pict-1.jpeg",
  "width": 680,
  "height": 680
}
,
3: {
  "image": 3,
  "url": "interpreter/pict-3.png",
  "width": 309,
  "height": 412
}
,
4: {
  "image": 4,
  "url": "interpreter/pict-4.png",
  "width": 450,
  "height": 361
}
,
5: {
  "image": 5,
  "url": "interpreter/pict-5.png",
  "width": 450,
  "height": 338
}
};
